### ISSUE TITLE
¿Qué es un horario?

### ISSUE THREAD

**Issue by puchy22** [shvtwp/cuidarDependencia#13]
- Es una serie de turnos de cuidado que corresponden a un familiar. Contemplado en la #3.
- Un horario tiene que estar pensado para una persona a atender. Contemplado en la #3.
- Se puede neceistar la ayuda de un profesional en caso de la no disponibilidad de ningún familiar, ya sea por incompatibilidad horaria o por necesidad de descanso. Contemplado en la #3.
- Las horas entre familiares se tienen que repartir de manera equitativa, es decir; los cuidadores con mayor disponibilidad se le asignarán más horas. Contemplado en la #6.
- En el caso de incluir a familiares jóvenes como nietos se le deben asignar la carga acorde con su edad, es decir asignar menos horas a este perfil. Contemplado en la #6.

**Comment by puchy22** [comment]
Hola @shvtwp he hecho unos cuantos issues con los distintos objetos valor y entidades que he obtenido de analizar las distntas HUs:memo:. Me gustaría que le echases un ojo antes de empezar a construir las distintas estructuras de datos, a ver si he entendido bien el dominio del problema y ves más o menos bien la solución que propongo para plantear el modelo.

Cualquier recomendación (como por ejemplo lo de la interfaz o clase abstracta del issue #11) respondemelo en ese mismo issue y a ver si así llegamos a la mejor solución posible. Un saludo :wave: :wave:.

**Comment by JJ** [comment]
Este es un ejemplo de un issue bien planteado, con todos los factores posibles, pero que desgraciadamente no parece que se haya resuelto bien. El commit [7a5714a](https://github.com/puchy22/DePendiente/commit/7a5714a85af8bd3d1bfc1827421d478e3338cc73), aparte de no seguir las buenas prácticas en su primera línea, no parece que aborde todos los problemas que aquí se presentan.
