### ISSUE TITLE
¿Qué es un turno de cuidado?

### ISSUE THREAD

**Issue by puchy22** [shvtwp/cuidarDependencia#14]
Un turno de cuidado se define como una fecha de inicio (día, mes, año y hora) y una duración en horas, con un límite máximo de horas indefinido contemplado en #3.

**Comment by JJ** [comment]
Todos los issues tienen que estar relacionados con una historia de usuario

**Comment by puchy22** [comment]
@JJ ¿si considero que este issue ya no es necesario porqué realmente no es un problema que se refleja en las historias de usuario sino que es más bien un tipo que se va a usar en los cuidadores puedo cerrarlo como "not planned" desde aquí o cómo procedo?

**Comment by JJ** [comment]
Plantear problemas siempre es necesario; otra cosa es que quieras solucionarlos en la forma como se sugiere el issue. Por eso debéis fijaros en problemas, no en conceptos o posibles ficheros. En ese sentido, en la modificación de código donde consideres que se resuelve este problema porque ya no es necesario especificar el intervalo horario, pon que se cierra este issue o directamente en el cuerpo del PR
