### ISSUE TITLE
Elegir lenguaje de programación

### ISSUE THREAD

**Issue by puchy22** [shvtwp/cuidarDependencia#8]
@shvtwp hay que elegir un lenguaje de programación para desarrollar el proyecto, es recomendable que se puedan definir estructuras de datos que serán necesarias para resolver el problema. Yo vería también recomendable que fuese un lenguaje fuertemente tipado para ahorrar mucho tiempo en el manejo de excepciones en próximos objetivos.

**Comment by shvtwp** [comment]
Hola @puchy22 , estoy de acuerdo, ¿tienes alguna preferencia?

**Comment by puchy22** [comment]
La verdad es que la mejor opción que veo es TypeScript ya que partiendo de que JavaScript a día de hoy es un lenguaje muy usado; partiendo de esto TypeScript añade muchas ventajas frente a este por ejemplo el tipado estático. Por esto creo que usado con con NodeJS o Deno es una buena opción.

**Comment by shvtwp** [comment]
Perfecto, TypeScript entonces.
